services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Madj2k\DrSeo\:
    resource: '../Classes/*'

  Madj2k\DrSeo\PageTitle\NewsTitleProvider:
    public: true

  Madj2k\DrSeo\PageTitle\WebsiteTitleProvider:
    public: true
